<input type="hidden" name="recipeName" value="<%=key.getRecipeName()%>">
<input type="hidden" name="imageUrl" value="<%=key.getImageUrl()%>">
<input type="hidden" name="moreInfoUrl" value="<%=key.getMoreInfoUrl()%>">
<input type="hidden" name="ingredientsList" value="<%=key.getIngredientsList() %>">
<input type="hidden" name="dietLabels" value="<%=key.getDietLabels() %>">
<input type="hidden" name="healthLabels" value="<%=key.getHealthLabels() %>">
<input type="hidden" name="calorieAmount" value="<%=key.getCalorieAmount()%>">
<input type="hidden" name="cookingTime" value="${cookingTime}">
<input type="hidden" name="createdBy" value="${userName}"/>