<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>


<link href="resources/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection" />
<link href="resources/css/style.css" type="text/css" rel="stylesheet"	media="screen,projection" />


<script src="resources/js/jquery/jQuery2.1.1.min.js"></script>
<script src="resources/js/materialize/materialize.js"></script>
<script src="resources/js/custom/init.js"></script>