<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>

<script type="text/javascript" src="<c:url value="/resources/js/jquery/jQuery2.1.1.min.js" />" ></script>
<script type="text/javascript" src="<c:url value="/resources/js/materialize/materialize.js" />" ></script>
<script type="text/javascript" src="<c:url value="/resources/js/custom/init.js" />" ></script>
<script type="text/javascript" src="<c:url value="/resources/js/custom/Ajaxcalls.js" />" ></script>
