<%@ include file="springResources.inc"%>

<script type="text/javascript" src="<c:url value="/resources/js/jquery/jQuery2.1.1.min.js" />" ></script>
<script type="text/javascript" src="<c:url value="/resources/js/materialize/materialize.js" />" ></script>
<script type="text/javascript" src="<c:url value="/resources/js/custom/init.js" />" ></script>
<script type="text/javascript" src="<c:url value="/resources/js/custom/Ajaxcalls.js" />" ></script>


<link href="<c:url value="/resources/css/materialize.css" />" type="text/css" rel="stylesheet" media="screen,projection">
<link href="<c:url value="/resources/css/style.css" />" type="text/css" rel="stylesheet" media="screen,projection">
